### ISSUE TITLE
Not working with the Latest Hestia Version.

### ISSUE THREAD

**Issue by poonam279** [HardeepAsrani/hestia-pricing-extension#1]
@HardeepAsrani With the latest version of Hestia, this plugin doesn't show the section to change the details of the third pricing table.

**Comment by HardeepAsrani** [comment]
Fixed with: https://github.com/HardeepAsrani/hestia-pricing-extension/commit/63ed97768109611d3f71541f04e3ba1b07a3140e

Thanks @poonam279
