### ISSUE TITLE
Installation / License

### ISSUE THREAD

**Issue by wadewilliams** [HardeepAsrani/hestia-pricing-extension#2]
Hello, 

 Thank you for this - 

 I'm trying to install, but I'm not sure exactly where to place this. I followed the Hestia tutorial and they recommend placing in a child theme under `inc/sections/hestia-pricing-section.php`, not sure if that's the intended location but I'm not seeing the extra pricing table show up yet. 

 Thanks! 

 Also a license file would be fantastic.

**Comment by HardeepAsrani** [comment]
@wadewilliams It's a plugin. The documentation is custom coding and this plugin is an alternative to that documentation. So if you want to use this, forget what the documentation tells you. :)

You can download the plugin from here: https://github.com/HardeepAsrani/hestia-pricing-extension/archive/master.zip

It will be a zip file. After that, navigate to Plugins > Add New > Upload, and upload this .zip file and activate it. Everything should work as expected. Let me know if it works properly. :)

**Comment by wadewilliams** [comment]
Thanks for answering my stupid question. Much appreciated!

**Comment by HardeepAsrani** [comment]
Glad to know. :)
